/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.adjacency-matrix[_ngcontent-%COMP%] {\r\n	margin: 20px auto 10px auto;\r\n	padding-right: 20px;\r\n	border-collapse: separate;\r\n	border-spacing: 8px;\r\n	text-align: center;\r\n	transform: translateX(-13px);\r\n}\r\n.header[_ngcontent-%COMP%] {\r\n	font-weight: bold;\r\n}\r\n.vertical-header[_ngcontent-%COMP%] {\r\n	transform: rotate(-90deg);\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZGlzcGxheS9hZGphY2VuY3ktbWF0cml4L2FkamFjZW5jeS1tYXRyaXguY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9QYXdlxYIvRGVza3RvcC9wcm9ncmFtb3dhbmllL2dyYXBocy1hcHAvc3JjL2FwcC9kaXNwbGF5L2FkamFjZW5jeS1tYXRyaXgvYWRqYWNlbmN5LW1hdHJpeC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
