/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './canvas.component';
const styles_CanvasComponent:any[] = ([] as any[]);
export const RenderType_CanvasComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CanvasComponent,
  data: {}
}
);
export function View_CanvasComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['This is the canvas component']))
  ]
  ,(null as any),(null as any));
}
function View_CanvasComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_CanvasComponent_0,RenderType_CanvasComponent)),
    import0.ɵdid(24576,(null as any),0,import1.CanvasComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CanvasComponentNgFactory:import0.ComponentFactory<import1.CanvasComponent> = import0.ɵccf('ng-component',import1.CanvasComponent,View_CanvasComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvY2FudmFzL2NhbnZhcy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvY2FudmFzL2NhbnZhcy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9QYXdlxYIvRGVza3RvcC9wcm9ncmFtb3dhbmllL2dyYXBocy1hcHAvc3JjL2FwcC9jYW52YXMvY2FudmFzLmNvbXBvbmVudC50cy5DYW52YXNDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL1Bhd2XFgi9EZXNrdG9wL3Byb2dyYW1vd2FuaWUvZ3JhcGhzLWFwcC9zcmMvYXBwL2NhbnZhcy9jYW52YXMuY29tcG9uZW50LnRzLkNhbnZhc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5UaGlzIGlzIHRoZSBjYW52YXMgY29tcG9uZW50PC9oMT4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJOzs7Ozs7SUNBSjtnQkFBQTs7OzsifQ==
