/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './graph-edit.component';
const styles_GraphEditComponent:any[] = ([] as any[]);
export const RenderType_GraphEditComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GraphEditComponent,
  data: {}
}
);
export function View_GraphEditComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Edit graph here']))
  ]
  ,(null as any),(null as any));
}
function View_GraphEditComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'graph-edit',([] as any[]),(null as any),(null as any),(null as any),View_GraphEditComponent_0,RenderType_GraphEditComponent)),
    import0.ɵdid(24576,(null as any),0,import1.GraphEditComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const GraphEditComponentNgFactory:import0.ComponentFactory<import1.GraphEditComponent> = import0.ɵccf('graph-edit',import1.GraphEditComponent,View_GraphEditComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtZWRpdC9ncmFwaC1lZGl0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9QYXdlxYIvRGVza3RvcC9wcm9ncmFtb3dhbmllL2dyYXBocy1hcHAvc3JjL2FwcC9ncmFwaHMvZ3JhcGgtbWVudS9ncmFwaC1lZGl0L2dyYXBoLWVkaXQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtZWRpdC9ncmFwaC1lZGl0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtZWRpdC9ncmFwaC1lZGl0LmNvbXBvbmVudC50cy5HcmFwaEVkaXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5FZGl0IGdyYXBoIGhlcmU8L3A+IiwiPGdyYXBoLWVkaXQ+PC9ncmFwaC1lZGl0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFHOzs7Ozs7SUNBSDtnQkFBQTs7OzsifQ==
