/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './graph-manipulate.component';
const styles_GraphManipulateComponent:any[] = ([] as any[]);
export const RenderType_GraphManipulateComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GraphManipulateComponent,
  data: {}
}
);
export function View_GraphManipulateComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Manipulate graph here']))
  ]
  ,(null as any),(null as any));
}
function View_GraphManipulateComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'graph-manipulate',([] as any[]),(null as any),(null as any),(null as any),View_GraphManipulateComponent_0,RenderType_GraphManipulateComponent)),
    import0.ɵdid(24576,(null as any),0,import1.GraphManipulateComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const GraphManipulateComponentNgFactory:import0.ComponentFactory<import1.GraphManipulateComponent> = import0.ɵccf('graph-manipulate',import1.GraphManipulateComponent,View_GraphManipulateComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtbWFuaXB1bGF0ZS9ncmFwaC1tYW5pcHVsYXRlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9QYXdlxYIvRGVza3RvcC9wcm9ncmFtb3dhbmllL2dyYXBocy1hcHAvc3JjL2FwcC9ncmFwaHMvZ3JhcGgtbWVudS9ncmFwaC1tYW5pcHVsYXRlL2dyYXBoLW1hbmlwdWxhdGUuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtbWFuaXB1bGF0ZS9ncmFwaC1tYW5pcHVsYXRlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUGF3ZcWCL0Rlc2t0b3AvcHJvZ3JhbW93YW5pZS9ncmFwaHMtYXBwL3NyYy9hcHAvZ3JhcGhzL2dyYXBoLW1lbnUvZ3JhcGgtbWFuaXB1bGF0ZS9ncmFwaC1tYW5pcHVsYXRlLmNvbXBvbmVudC50cy5HcmFwaE1hbmlwdWxhdGVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5NYW5pcHVsYXRlIGdyYXBoIGhlcmU8L3A+IiwiPGdyYXBoLW1hbmlwdWxhdGU+PC9ncmFwaC1tYW5pcHVsYXRlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFHOzs7Ozs7SUNBSDtnQkFBQTs7OzsifQ==
